export interface MuscleGroup {
  id: string;
  name: string;
  view: "front" | "back";
  shape: "ellipse" | "rect" | "path";
  // For ellipse: cx, cy, rx, ry
  // For rect: x, y, width, height, rx (border-radius)
  attrs: Record<string, number | string>;
}

export const FRONT_MUSCLES: MuscleGroup[] = [
  {
    id: "head",
    name: "Cabeza",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 100, cy: 40, rx: 26, ry: 28 },
  },
  {
    id: "neck",
    name: "Cuello",
    view: "front",
    shape: "rect",
    attrs: { x: 90, y: 66, width: 20, height: 20, rx: 4 },
  },
  {
    id: "left-shoulder",
    name: "Hombro izquierdo",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 62, cy: 100, rx: 18, ry: 14 },
  },
  {
    id: "right-shoulder",
    name: "Hombro derecho",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 138, cy: 100, rx: 18, ry: 14 },
  },
  {
    id: "chest",
    name: "Pecho",
    view: "front",
    shape: "rect",
    attrs: { x: 78, y: 88, width: 44, height: 44, rx: 6 },
  },
  {
    id: "abs",
    name: "Abdomen",
    view: "front",
    shape: "rect",
    attrs: { x: 82, y: 132, width: 36, height: 36, rx: 4 },
  },
  {
    id: "left-oblique",
    name: "Oblicuo izquierdo",
    view: "front",
    shape: "rect",
    attrs: { x: 64, y: 128, width: 16, height: 32, rx: 4 },
  },
  {
    id: "right-oblique",
    name: "Oblicuo derecho",
    view: "front",
    shape: "rect",
    attrs: { x: 120, y: 128, width: 16, height: 32, rx: 4 },
  },
  {
    id: "left-bicep",
    name: "Bíceps izquierdo",
    view: "front",
    shape: "rect",
    attrs: { x: 46, y: 106, width: 16, height: 44, rx: 6 },
  },
  {
    id: "right-bicep",
    name: "Bíceps derecho",
    view: "front",
    shape: "rect",
    attrs: { x: 138, y: 106, width: 16, height: 44, rx: 6 },
  },
  {
    id: "left-forearm",
    name: "Antebrazo izquierdo",
    view: "front",
    shape: "rect",
    attrs: { x: 40, y: 150, width: 14, height: 42, rx: 5 },
  },
  {
    id: "right-forearm",
    name: "Antebrazo derecho",
    view: "front",
    shape: "rect",
    attrs: { x: 146, y: 150, width: 14, height: 42, rx: 5 },
  },
  {
    id: "left-hand",
    name: "Mano izquierda",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 47, cy: 206, rx: 10, ry: 12 },
  },
  {
    id: "right-hand",
    name: "Mano derecha",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 153, cy: 206, rx: 10, ry: 12 },
  },
  {
    id: "groin",
    name: "Ingle / Cadera",
    view: "front",
    shape: "rect",
    attrs: { x: 82, y: 168, width: 36, height: 18, rx: 4 },
  },
  {
    id: "left-quad",
    name: "Cuádriceps izquierdo",
    view: "front",
    shape: "rect",
    attrs: { x: 78, y: 186, width: 20, height: 62, rx: 6 },
  },
  {
    id: "right-quad",
    name: "Cuádriceps derecho",
    view: "front",
    shape: "rect",
    attrs: { x: 102, y: 186, width: 20, height: 62, rx: 6 },
  },
  {
    id: "left-knee",
    name: "Rodilla izquierda",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 88, cy: 260, rx: 12, ry: 11 },
  },
  {
    id: "right-knee",
    name: "Rodilla derecha",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 112, cy: 260, rx: 12, ry: 11 },
  },
  {
    id: "left-shin",
    name: "Espinilla izquierda",
    view: "front",
    shape: "rect",
    attrs: { x: 80, y: 271, width: 14, height: 52, rx: 5 },
  },
  {
    id: "right-shin",
    name: "Espinilla derecha",
    view: "front",
    shape: "rect",
    attrs: { x: 106, y: 271, width: 14, height: 52, rx: 5 },
  },
  {
    id: "left-ankle",
    name: "Tobillo izquierdo",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 87, cy: 333, rx: 10, ry: 8 },
  },
  {
    id: "right-ankle",
    name: "Tobillo derecho",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 113, cy: 333, rx: 10, ry: 8 },
  },
  {
    id: "left-foot",
    name: "Pie izquierdo",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 84, cy: 352, rx: 14, ry: 9 },
  },
  {
    id: "right-foot",
    name: "Pie derecho",
    view: "front",
    shape: "ellipse",
    attrs: { cx: 116, cy: 352, rx: 14, ry: 9 },
  },
];

export const BACK_MUSCLES: MuscleGroup[] = [
  {
    id: "head-back",
    name: "Cabeza (posterior)",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 100, cy: 40, rx: 26, ry: 28 },
  },
  {
    id: "neck-back",
    name: "Cuello (posterior)",
    view: "back",
    shape: "rect",
    attrs: { x: 90, y: 66, width: 20, height: 20, rx: 4 },
  },
  {
    id: "left-trapezius",
    name: "Trapecio izquierdo",
    view: "back",
    shape: "rect",
    attrs: { x: 62, y: 86, width: 20, height: 34, rx: 4 },
  },
  {
    id: "right-trapezius",
    name: "Trapecio derecho",
    view: "back",
    shape: "rect",
    attrs: { x: 118, y: 86, width: 20, height: 34, rx: 4 },
  },
  {
    id: "upper-back",
    name: "Espalda alta",
    view: "back",
    shape: "rect",
    attrs: { x: 80, y: 86, width: 40, height: 36, rx: 4 },
  },
  {
    id: "mid-back",
    name: "Espalda media",
    view: "back",
    shape: "rect",
    attrs: { x: 82, y: 122, width: 36, height: 30, rx: 4 },
  },
  {
    id: "lower-back",
    name: "Espalda baja / Lumbar",
    view: "back",
    shape: "rect",
    attrs: { x: 82, y: 152, width: 36, height: 28, rx: 4 },
  },
  {
    id: "left-tricep",
    name: "Tríceps izquierdo",
    view: "back",
    shape: "rect",
    attrs: { x: 44, y: 106, width: 16, height: 44, rx: 6 },
  },
  {
    id: "right-tricep",
    name: "Tríceps derecho",
    view: "back",
    shape: "rect",
    attrs: { x: 140, y: 106, width: 16, height: 44, rx: 6 },
  },
  {
    id: "left-forearm-back",
    name: "Antebrazo izquierdo",
    view: "back",
    shape: "rect",
    attrs: { x: 40, y: 150, width: 14, height: 42, rx: 5 },
  },
  {
    id: "right-forearm-back",
    name: "Antebrazo derecho",
    view: "back",
    shape: "rect",
    attrs: { x: 146, y: 150, width: 14, height: 42, rx: 5 },
  },
  {
    id: "left-hand-back",
    name: "Mano izquierda",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 47, cy: 206, rx: 10, ry: 12 },
  },
  {
    id: "right-hand-back",
    name: "Mano derecha",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 153, cy: 206, rx: 10, ry: 12 },
  },
  {
    id: "left-glute",
    name: "Glúteo izquierdo",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 88, cy: 204, rx: 20, ry: 20 },
  },
  {
    id: "right-glute",
    name: "Glúteo derecho",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 112, cy: 204, rx: 20, ry: 20 },
  },
  {
    id: "left-hamstring",
    name: "Isquiotibial izquierdo",
    view: "back",
    shape: "rect",
    attrs: { x: 78, y: 224, width: 20, height: 60, rx: 6 },
  },
  {
    id: "right-hamstring",
    name: "Isquiotibial derecho",
    view: "back",
    shape: "rect",
    attrs: { x: 102, y: 224, width: 20, height: 60, rx: 6 },
  },
  {
    id: "left-knee-back",
    name: "Rodilla izquierda (posterior)",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 88, cy: 295, rx: 12, ry: 11 },
  },
  {
    id: "right-knee-back",
    name: "Rodilla derecha (posterior)",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 112, cy: 295, rx: 12, ry: 11 },
  },
  {
    id: "left-calf",
    name: "Pantorrilla izquierda",
    view: "back",
    shape: "rect",
    attrs: { x: 80, y: 306, width: 14, height: 50, rx: 5 },
  },
  {
    id: "right-calf",
    name: "Pantorrilla derecha",
    view: "back",
    shape: "rect",
    attrs: { x: 106, y: 306, width: 14, height: 50, rx: 5 },
  },
  {
    id: "left-heel",
    name: "Talón izquierdo",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 87, cy: 365, rx: 10, ry: 8 },
  },
  {
    id: "right-heel",
    name: "Talón derecho",
    view: "back",
    shape: "ellipse",
    attrs: { cx: 113, cy: 365, rx: 10, ry: 8 },
  },
];
